### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by Hugman76**

### CODE REVIEW

**Review by thecatcore — APPROVED** [review]

**Review by thecatcore — APPROVED** [review]

**Comment by RedstoneParadox** [comment]
I'm going to wait to merge this because I still have a few things planned that I'm going to need translations for.

**Comment by Hugman76** [comment]
Alright, tell us when the lang file is finished and I'll update the PR. 😄

**Comment by RedstoneParadox** [comment]
Cut a few of the features I had initially planned to be ready for the playtest due to time. If you want to go ahead with the translations anyways, I can merge them.

**Comment by Hugman76** [comment]
It's ready now

**Pull request merged**
